name: restart-blockscout

on:
  workflow_dispatch:

jobs:
  restart-blockscout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Blockscout
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            sudo -s
            cd blockscout-backend/
            git pull
            git checkout midl
            . /root/.asdf/asdf.sh
            screen -dmS blockscout bash -c ". /root/.asdf/asdf.sh && tail -1 /home/ubuntu/blockscout-backend/env.sh | sh"
          EOF
