name: blockscout

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Blockscout
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd blockscout-backend/
            sudo -s
            git pull
            git checkout midl
            mix compile --force
            screen -S blockscout -X quit
            sleep 5
            screen -dmS blockscout bash -c "tail -1 env.sh | sh"
          EOF
